# Generated by Django 4.1.2 on 2024-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_mensaje_comentario_mensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('fecha_nocimiento', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('confirmar_contrasenia', models.CharField(max_length=100)),
                ('genero', models.IntegerField(choices=[(1, 'masculino'), (2, 'femenino'), (3, 'otro')])),
                ('direccion', models.CharField(max_length=1000)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
